In [2]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 2.04760404  0.99188809 -2.04559875  1.35901081 -0.37030407]


In [3]:
#rank 1 array >> Don't use
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 2.04760404  0.99188809 -2.04559875  1.35901081 -0.37030407]


In [5]:
print(np.dot(a,a.T))

11.345034002227612


In [7]:
a = np.random.randn(5,1) #a.shaep = (5,1) >> Column vector
print(a)

[[ 0.09033125]
 [-0.12700205]
 [-1.37805238]
 [ 0.02488235]
 [-0.35556631]]


In [8]:
#1x5 matrix
print(a.T)

[[ 0.09033125 -0.12700205 -1.37805238  0.02488235 -0.35556631]]


In [9]:
print(np.dot(a,a.T))

[[ 8.15973427e-03 -1.14722535e-02 -1.24481190e-01  2.24765356e-03
  -3.21187488e-02]
 [-1.14722535e-02  1.61295204e-02  1.75015476e-01 -3.16010922e-03
   4.51576505e-02]
 [-1.24481190e-01  1.75015476e-01  1.89902836e+00 -3.42891793e-02
   4.89989006e-01]
 [ 2.24765356e-03 -3.16010922e-03 -3.42891793e-02  6.19131257e-04
  -8.84732490e-03]
 [-3.21187488e-02  4.51576505e-02  4.89989006e-01 -8.84732490e-03
   1.26427404e-01]]


In [ ]:
assert(a.shape == (5,1)) #a.shaep = (5,1) >> Column vector